In [1]:
import pandas as pd

In [49]:
df1 = pd.read_csv('Fotocasa.csv', delimiter=',')#, parse_dates=[6], nrows = nRowsRead)
df1.create_date = pd.to_datetime(df1.create_date, errors='coerce', format='%d/%m/%Y %H:%M:%S', dayfirst=True)

In [54]:
df1.head(5)

,phone,featuresValues,planta,ABTest,ad_id,promotion_id,ad_publisher_type_id,ads_name_page,city,city_id,...,country,country_id,create_date,district,event_name,features,image_urls,full_description,url,images
0,932753425,"""terraza,balcon,lavadero""",3ª planta,NaN,147462618,0,1,fotocasaes/tv/ficha,Sitges,8270,...,España,724,2018-06-27 19:24:11,La Devesa- El Poble-sec - La Vista Alegre,detail,featuresValues,['https://d.inmofactory.com/1/101539/14909724/...,¿Te apetece acabar de reformar esta vivienda y...,https://www.fotocasa.es/vivienda/sitges/sitges...,[{'url': 'https://d.inmofactory.com/1/101539/1...
1,944943352,"""armarios,calefaccion,terraza,ascensor,amuebla...",4ª planta,NaN,149843274,0,1,fotocasaes/tv/ficha,Bilbao,48020,...,España,724,2019-02-01 13:59:08,Begoña,detail,featuresValues,['https://d.inmofactory.com/1/100148/16391250/...,DT INMOBILIARIA TE OFRECE EN EXCLUSIVA PRECIOS...,https://www.fotocasa.es/vivienda/bilbao/calefa...,[{'url': 'https://d.inmofactory.com/1/100148/1...
2,952140746,"""aire-acondicionado,armarios,calefaccion,garaj...",NaN,NaN,149873085,0,1,fotocasaes/tv/ficha,Marbella,29069,...,España,724,2019-02-05 05:32:19,Las Chapas,detail,featuresValues,['https://d.inmofactory.com/1/113633/16407761/...,Luminosa vivienda en planta baja de dos dormit...,https://www.fotocasa.es/vivienda/marbella/aire...,[{'url': 'https://d.inmofactory.com/1/113633/1...
3,928194387,"""""",NaN,NaN,149997962,0,1,fotocasaes/tv/ficha,Agüimes,35002,...,España,724,2019-02-13 22:00:54,NaN,detail,featuresValues,['https://d.inmofactory.com/1/109844/16495350/...,"Casa de una sola planta 100 metros cuadrados, ...",https://www.fotocasa.es/vivienda/aguimes/aguim...,[{'url': 'https://d.inmofactory.com/1/109844/1...
4,912172763,"""aire-acondicionado,armarios,calefaccion,garaj...",NaN,NaN,148366355,0,1,fotocasaes/tv/ficha,Arganda del Rey,28014,...,España,724,2018-09-20 17:04:20,Centro,detail,featuresValues,['https://d.inmofactory.com/1/98287/15422414/1...,Chalet adosado en venta en Arganda del Rey. Zo...,https://www.fotocasa.es/vivienda/arganda-del-r...,[{'url': 'https://d.inmofactory.com/1/98287/15...

In [14]:
df1.columns

Index(['phone', 'featuresValues', 'planta', 'ad_id', 'promotion_id',
       'ad_publisher_type_id', 'ads_name_page', 'city', 'city_id', 'city_zone',
       'company_idwas', 'county', 'county_id', 'district_id', 'mts2',
       'mts2_max', 'mts2_min', 'neighbourhood', 'neighbourhood_id',
       'postal_code', 'price', 'price_max', 'price_min', 'property',
       'property_id', 'property_state', 'property_state_id', 'property_sub',
       'property_sub_id', 'query', 'region_level2', 'region_level2_id',
       'reload', 'rooms', 'search_terms', 'site', 'street', 'transaction_id',
       'water_id', 'ad_publisher_id', 'ad_publisher_type', 'ad_title',
       'bathrooms', 'city_zone_id', 'country', 'country_id', 'create_date',
       'district', 'event_name', 'features', 'image_urls', 'full_description',
       'url', 'images'],
      dtype='object')

In [16]:
del df1['features_id']
del df1['ads_name_page']

In [63]:
data = df1[['phone', 'featuresValues', 'planta', 'ad_id', 'promotion_id',
       'ad_publisher_type_id', 'city', 'city_id', 'city_zone', 'county', 'county_id', 'district_id', 'mts2',
       'mts2_max', 'mts2_min', 'neighbourhood', 'neighbourhood_id',
       'postal_code', 'price', 'price_max', 'price_min', 'property',
       'property_id', 'property_state', 'property_state_id', 'property_sub',
       'property_sub_id', 'query', 'region_level2', 'region_level2_id',
       'reload', 'rooms', 'search_terms', 'site', 'street', 'transaction_id',
       'water_id', 'ad_publisher_id', 'ad_publisher_type', 'ad_title',
       'bathrooms', 'city_zone_id', 'create_date',
       'district', 'full_description']]

In [71]:
data.apply(func=)

TypeError: max expected 1 arguments, got 0